Description: "Create garbage classification notebook instance"
Resources:
  RecycleClassifier:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t2.xlarge"
      RoleArn: !GetAtt ExecutionRole.Arn
      AdditionalCodeRepositories: ["https://github.com/kbb29/recycle.git"]
  ExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "sagemaker.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSageMakerFullAccess"
Outputs:
  RecycleClassifierId:
    Value: !Ref RecycleClassifier
